- name: Disable current versio of mysql
  ansible.builtin.command: dnf module disable mysql -y

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
  
- name: Install MySql
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start & Enable MySql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
  