- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Install dependecies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Rename jar file 
  ansible.builtin.command: "mv target/{{host_name}}-{{shipping_version}}.jar {{host_name}}.jar"
  args:
    chdir: /app